sudo: true
language: erlang
otp_release:
  - 18.0
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential git pkg-config libmagickwand-dev
script: "./rebar3 as prod tar"
